### ISSUE TITLE
Exception when invoking FingerprintAPI getEvent() method

### ISSUE THREAD

**Issue by jlagunilla** [fingerprintjs/fingerprint-pro-server-api-java-sdk#21]
Hi, I'm trying to test the SDK and I get the following exception when invoking the getEvent() method on the FingerprintApi class.

```
java.lang.AbstractMethodError: Receiver class com.sun.jersey.api.uri.UriBuilderImpl does not define or inherit an implementation of the resolved method 'abstract javax.ws.rs.core.UriBuilder uri(java.lang.String)' of abstract class javax.ws.rs.core.UriBuilder.
        at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:96)
        at org.glassfish.jersey.client.JerseyWebTarget.<init>(JerseyWebTarget.java:50)
        at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:274)
        at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:56)
        at com.fingerprint.sdk.ApiClient.invokeAPI(ApiClient.java:1000)
        at com.fingerprint.api.FingerprintApi.getEventWithHttpInfo(FingerprintApi.java:133)
        at com.fingerprint.api.FingerprintApi.getEvent(FingerprintApi.java:78)
```
I'm using Gradle and added the dependency as per your documentation. Is there anything that I'm missing?

Any help would be greatly appreciated.

**Comment by ilfa** [comment]
Hi @jlagunilla!
Can you provide more information about your environment? I'm interested in OS, Java, and Gradle versions.
Maybe we missed something, and something in your environment is different with the `Jersey` library.

Thank you.

**Comment by jlagunilla** [comment]
Hi! Thank you for your quick reply.

I'm running my code in the following environment:

- OS: Debian 4.9.0-19-amd64.
- Application server: Apache Tomcat 9.0.43.
- JVM version: 11.0.18+10-post-Debian-1deb11u1
- Gradle version: 7.3

**Comment by jlagunilla** [comment]
Good morning!

Just in case you also need the environment in which I'm running my IDE, here it is:

- OS: Windows 10
- IDE: Eclipse 2021-06
- JDK: jdk-11.0.15.10-hotspot
- Gradle version: 7.3

Thanks!

**Comment by ilfa** [comment]
Can you check your project dependencies?
We are mostly interested in [jersey-client](https://mvnrepository.com/artifact/org.glassfish.jersey.core/jersey-client). Looks like you are using one with a version lower than `2.35`.

Thank you!

**Comment by jlagunilla** [comment]
Hi Ilya!

You were absolutely right, there was another dependency also using Jersey Client, version 1.19, and thus interfering with your library. Now I get the following error:

`Exception: {"error":{"code":"TokenNotFound","message":"secret key is not found"}}com.fingerprint.sdk.ApiException: {"error":{"code":"TokenNotFound","message":"secret key is not found"}}`

which is the JSON I was expecting.

Thank you very much for your help!

**Comment by ilfa** [comment]
Glad that you managed to find out so fast!
